image: Visual Studio 2017

version: 1.0.{build}
       
environment:
  SONAR_TOKEN:
    secure: 7erJjZzqC/gHB5rNZ1aC/CDpHjrlnDT9rQX+CB7A30h5F34LB4jcibonoE7PvsYs
  GITHUB_ACCESS_TOKEN:
    secure: uj8259rTzhBmAdk/WjTMFBW69/ic/W4fC2OxxVxKDYnqTdzM7x4BYumGK5zvxfip

branches:
  only:
    - master

# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true

configuration: Release
platform: Any CPU

install:
  # compute version
  - ps: . .\build\ComputeVersion.ps1
  - ps: $version = Compute "Alm\Alm.csproj" $env:APPVEYOR_BUILD_NUMBER ([System.Convert]::ToBoolean($env:APPVEYOR_REPO_TAG)) $env:APPVEYOR_PULL_REQUEST_NUMBER
  - ps: Update-AppveyorBuild -Version $version.Semver
  - ps: $env:Prefix = $version.Prefix
  - ps: $env:Suffix = $version.Suffix
  - choco install "msbuild-sonarqube-runner" -y
  - choco install opencover.portable
  - choco install codecov


dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'

before_build:
- dotnet restore
- cmd: >-
    IF "%APPVEYOR_PULL_REQUEST_NUMBER%"=="" (
    C:\ProgramData\chocolatey\lib\msbuild-sonarqube-runner\tools\MSBuild.SonarQube.Runner.exe begin /k:"Alm" /d:"sonar.analysis.mode=publish" /d:"sonar.host.url=https://sonarcloud.io" /d:"sonar.organization=rducom-github" /d:"sonar.login=%SONAR_TOKEN%"
    ) ELSE (
    C:\ProgramData\chocolatey\lib\msbuild-sonarqube-runner\tools\MSBuild.SonarQube.Runner.exe begin /k:"Alm" /d:"sonar.analysis.mode=preview" /d:"sonar.host.url=https://sonarcloud.io" /d:"sonar.organization=rducom-github" /d:"sonar.login=%SONAR_TOKEN%" /d:"sonar.github.pullRequest=%APPVEYOR_PULL_REQUEST_NUMBER%" /d:"sonar.github.repository=rducom/ALM" /d:"sonar.github.oauth=%GITHUB_ACCESS_TOKEN%"
    )

build_script:
- cmd: >-
     msbuild "C:\projects\alm\Alm.sln" /m /verbosity:minimal /property:VersionPrefix=%Prefix%;VersionSuffix=%Suffix% /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

after_build:
- cmd: >-
    "C:\ProgramData\chocolatey\lib\msbuild-sonarqube-runner\tools\MSBuild.SonarQube.Runner.exe" end /d:"sonar.login=%SONAR_TOKEN%"
- cmd: >-
    dotnet pack Alm\Alm.csproj --configuration %CONFIGURATION% /p:PackageVersion="%APPVEYOR_BUILD_VERSION%" -o artifacts

test_script:
- OpenCover.Console.exe -returntargetcode -oldstyle -register:user -target:"C:\Program Files\dotnet\dotnet.exe" -targetargs:"test /p:DebugType=full -c Debug .\Alm.Test\Alm.Test.csproj" -filter:"+[Alm*]* -[Alm.Test*]*" -excludebyattribute:"*.ExcludeFromCodeCoverage*" -output:coverage-opencover.xml
- codecov -f coverage-opencover.xml

artifacts:
  - path: Alm\artifacts\*.nupkg
    name: lib

deploy:

- provider: NuGet
  api_key:
    secure: pI7g9o0ov/i6LAUL4sOH9WsVniseBdJE4GRFlpXicLn6zJWCNPsamsi+/qgAqCFn
  skip_symbols: true
  artifact: /.*\.nupkg/
  on:
    branch: master
    deploy_public: true
     
- provider: NuGet
  server: https://ci.appveyor.com/nuget/raph-r95r21ggl8dg
  api_key:
    secure: JmWl2yOQSj9MLgHSmA1tHywqEsMktEO7PvKR+roJvRg=
  skip_symbols: false
  artifact: /.*\.nupkg/
  on:
    deploy_unstable: true